---
test:
  azure_defaults: &azure_defaults
    client_id: AZURE_CLIENT_ID
    client_secret: AZURE_CLIENT_SECRET
    tenant_id: AZURE_TENANT_ID
    subscription_id: AZURE_SUBSCRIPTION_ID
  azure:
    <<: *azure_defaults
